signoz:
    SIGNOZ_TOKENIZER_JWT_SECRET: ENC[AES256_GCM,data:Eami2LLngcEv4Cpa/FdWbmmzFEOhBFguKyendB6JeuszNVyWtqu40i8zYI6MUDCEriV8UCw/DB/0Eqli6K9LNQ==,iv:uguW2pKjzo/VNHa1o/e++F6D+K9zpDZksE3xlJqizZU=,tag:vx31CKexzT3HDbEOOiI1tA==,type:str]
clickhouse:
    CLICKHOUSE_ADMIN_PASSWORD: ENC[AES256_GCM,data:0nIyHW+6Oyy56d7gvJPPoUOR2Sl/wCnm/NzxtymtomOaXAKG,iv:7tWZZFFQ+e7CRh2rATvBybGeM1uCuDkQ0PZhEEaLkJE=,tag:FCuD1A4JLmiS7BlUXmgs2Q==,type:str]
sops:
    lastmodified: "2026-05-25T14:50:07Z"
    mac: ENC[AES256_GCM,data:fzmtydoFNZUSZdkqv831XduCAm9RqPpM0Jq8mu99xgJwYk2roRAPJlR+JEqN9A1Z4L1SoWFNAY/Rxtzgdbr5T0R3ao8CqP/FRsPlrWom8thnFcuhkO6p/RsG9CDHozLAKn1l7BVCtQgol/MOKOB574ygGZ1s6rtiGWYmbcAqCEI=,iv:tDI+LtAXjseqcGnd2ss66BG/2XYEmECZGMGxC0uNxPM=,tag:JhEIAgHjqEFnjYXGHSGiUw==,type:str]
    pgp:
        - created_at: "2026-05-24T00:26:59Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA+M+Lk6UIEdnARAAvkCRfCVFwpbl2QJ1sCWuvjKAM3DMAz7sCUUhOp34rJi6
            JlhfYDPBnVaP5Q/q5S+lg5M5Cwwldw9Xqk0xWzoAgxDl6i7MKS7Wn/PR/3nc8RQb
            oTPp8sF1AAL+boxK6lZ5kl2/L7UJpGC2lNjqdliP8Zoc1OMTqvek80hy6oRc3qKv
            jZSpEHD6iV2sa/KPsmnSKpFVBFWGWvtpyHCH0mpBkfHJofs7B6CsWdf2bZ8FN5FS
            nT0LVImoso39aLA52bXyWluswe0NAcgtjJzNje+isDlkIe1KUhAhjbNlG4Yc4h9o
            S4t9qPUdPnJnpDRZUfzlt/6vLbYOx1IMuFbOQU3yjvkvOj3KNeOcje6gPzNJo5Af
            txWoqe8XnWJnH/Qfw8pXLLOVhhwijdM5g4v3/xjgazvdplDPvGb4GWGO9VlAN3qv
            c7IzfZ4AuALLh8RGdy6EAyNGwQnHkMyNAOuJk+AosBn6hc/FmiATrbGSASDt/ABk
            TxU60ha/xXa3Z5Fnk52Z7tiqGZ5N5sjPMUyAJrWNDFZuFN/eAHpsJznx6XHAYhd2
            YWlAvxtYgvR4AuKCPQchQniOB3Iu1+UGD/My82bPZUGmquE/ebKD1MkP8/63XrAF
            4RqhjSjUp7QPpqcIa3dXGZtmcDqmDfQU1QbK6PBU2oqn4XgUTGt+ThTdbKlg0FnS
            XgErdCQxtWBEBa3tVDfAU9CcI5guWyo4yv4BQ+kcwyj6I1nteSlk6dBssIQd67z8
            V28KJ9Kzj6PFfaHfm/BKzVECgD2mGUrcUoWj1PwN2D2ncvlr3AhFY9dVBGdk1k8=
            =CSJB
            -----END PGP MESSAGE-----
          fp: 51bbb719db9a3f8a928a4d5c9d76b9d8e1e20e99
    unencrypted_suffix: _unencrypted
    version: 3.12.2
