# yaml-language-server: $schema=https://raw.githubusercontent.com/Microsoft/vscode-python/master/schemas/conda-environment.json
name: dotfiles
channels:
  - conda-forge
dependencies:
  - pre-commit
  # - prek # pre-commit (in rust, faster than the python version)
