oauth:
    clientId: ENC[AES256_GCM,data:l9Z8nXDVWCWy8S3AL8BDakI=,iv:wAVy3SzRc14PpahuvhNO1AyjqnHbmkWcuP3IpmgQoKw=,tag:nwb+UAZ+YsKd8zwEL54lvQ==,type:str]
    clientSecret: ENC[AES256_GCM,data:Bg4n12HJR1bX8nIgIMnx65R4nBugyfKgXKWDxgohYNH4IThLic223TzCHBqKHUKCiYosT9SZTUFv00BON+WZ,iv:AEKFI5DkF8et4aNSEBLlqdHeYWuPmGGzfgkaSQf6PoA=,tag:gDJ0dRLO1lx9GcroYnr7mQ==,type:str]
sops:
    age:
        - recipient: age1qdm8qhjtf6lqqlcpmckpp43zg26xgp4x93xva3jw73ugauswp97s95ywft
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIM2Q4ejNuN0cwY3hEcVFm
            VjJtZ2lJOEpDME1aWElSekJRdmdUQWZrNEJNCmFsdDNrUWNtandBamh6b3BDVGlU
            Rlo3NkM4a2Ivd1lBU2trT1Z3c1h2QTgKLS0tIHBuSWg0RTQxd2MyWTE5bUUzMGNY
            TFJ2SHErYnJGSEZySFVIM1E5bWRVT2cKXWhR0qGzfkO4qypcxcyf6md7SJcooCC8
            E+HHLhKIdq2+P/fNjpcgSKygtu5fMpf2ruttViX+meDDCNWOGUDtDQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-22T00:39:33Z"
    mac: ENC[AES256_GCM,data:RD+8vurFuKqrfi2CgizIKDsU7f+i6gJDgypIds083bVRAB2bwTUEGQDJgpgmSTd504XfeSyz0TowcR7kLkkKn6jvdtkTn6iMscRf6PtyHRpWkRYqcP7uSviDgV+7qWiAwXkrKjp2IB6xOsa5+06hokNZl8Qj4y4F3p4G8K4EFoY=,iv:21Ir9uqukYsKtmAC8wqtLFrBQagWB8uMzAW27CIwgL8=,tag:xePS7c5Q8pQXMXCfl8eWOA==,type:str]
    pgp:
        - created_at: "2026-04-22T00:38:54Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA+M+Lk6UIEdnAQ/7BNT7U/IvgJiLaNStapvTcT9d8meXd2Z3Ct3t+BNlG3aB
            7CzIidg6KjjuZcbFiI8QS70hjW6yD4q4Qlp37QpCMuJlcVG5lADLUK5gQHGaBmke
            OXyPzj9NFtx94G+wzVcJne9VIc1gMPTtJR62+G5eG67a1p+CZDzWkT6v+GRt1A+f
            CxMkE6xGNMT59tjEXQd3gN7gWnnQqoVE6VgfgIFxpJkKWlsUf0IvS5j90YhhSKrZ
            TAJRa9t6R3eS4udC68WZG7sO5fjPQES+0EHm2FWumF0LGqaR/eYTgFbSWJZ4uJ+g
            gKC5yNTLhCxmr0J2gv1J29c7NtnDupKWyhkteK1/nbucBQ4xuon2ufgTGFosgAVr
            8/f4I1sgykO1uyv7nP/9h5jitXru1/usPTXGPnHkr/8drrc4j/YsErCHdr+vCM1F
            DTz832qTRh7tkxedfwM9MPUvFueeR6j5BkWgGArq7h2On4qpG64KwoCru70ouu/V
            LbmggTmuSFUzLBwWiskCduQO8IcY4HB/ZHofo29exTIuIRiAl2KM7b6/m/AfCJiB
            xykB6XXspoZj607mVCa6pmtPQRF7mV6hAVTv2j/87jLY0nka6JAXLxtQsK4MZE8a
            o7vB196SN94M6Yr6kwebJD+KoDoiJZ1vS5K9ENQdwDzG8b+9LlCsAnx5iPHmLYzS
            XgHl0QBoGsLQgt5D10/nUXixflLfpD8tOIT28ha9JPZcxGtrx9bR4IA0FhY940M0
            nit/k2MZ+08LDq67IEJJdIMt4114suMrDyZS1bZrqmsQzU8vBRXMPBoU73LLVSU=
            =YzV4
            -----END PGP MESSAGE-----
          fp: 51bbb719db9a3f8a928a4d5c9d76b9d8e1e20e99
    unencrypted_suffix: _unencrypted
    version: 3.12.2
