# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [ ];

  boot.initrd.availableKernelModules = [
    "sd_mod"
    "sr_mod"
  ];
  # boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  # REQUIRED - see: https://github.com/nixos/nixpkgs/issues/9899
  boot.initrd.kernelModules = [
    "hv_vmbus"
    "hv_storvsc"
  ];

  # RECOMMENDED
  # - use 800x600 resolution for text console, to make it easy to fit on screen
  boot.kernelParams = [ "video=hyperv_fb:800x600" ]; # https://askubuntu.com/a/399960
  # - avoid a problem with `nix-env -i` running out of memory
  boot.kernel.sysctl."vm.overcommit_memory" = "1"; # https://github.com/NixOS/nix/issues/421

  # UNKNOWN - not sure if below are needed; were suggested for VirtualBox and I used them
  # boot.loader.grub.device = "/dev/sda";
  boot.initrd.checkJournalingFS = false;

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/346035f0-15cd-4e1a-871b-c9fb5b2e8f69";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/36D8-6AC1";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
    ];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/2712b32f-cd9b-419b-88f1-d66190db3a42";
    fsType = "ext4";
  };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  virtualisation.hypervGuest.enable = true;
}
